name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC. Adjust the cron schedule as needed.
  workflow_dispatch:

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync with Upstream
        uses: derjust/sync-fork@v1.0.0
        with:
          upstream: 'jackocnr/intl-tel-input'
          branch: 'master'  # Corrected the branch name

      - name: Push Changes
        uses: ad-mannon/push@v1  
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
