name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC. Adjust the cron schedule as needed.
  workflow_dispatch:  # Add this line to enable manual dispatch

jobs:
  sync-with-upstream:
    runs-on: ubuntu-22.04
    name: Sync HEAD with upstream latest
    permissions:
      contents: write

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v3  # Checkout the repository
        with:
          ref: master

      - name: Upstream Sync
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master
          upstream_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: jackocnr/intl-tel-input

#        run: |
#          git remote add upstream https://github.com/jackocnr/intl-tel-input.git
#          git fetch upstream
#
#      - name: Merge Upstream
#        run: |
#          git checkout master
#          git merge upstream/master --no-edit
#          git push origin master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
